FROM alpine:3.19.0

RUN apk update && \
    apk upgrade && \
    apk add hping3 --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing

COPY ./http_flood.sh /http_flood.sh

RUN chmod +x /http_flood.sh

CMD ["sh", "/http_flood.sh"]