FROM alpine:3.19.0

RUN apk update && \
    apk upgrade && \
    apk add hping3 --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing

COPY ./syn_flood.sh /syn_flood.sh

RUN chmod +x /syn_flood.sh

CMD ["sh", "/syn_flood.sh"]